12:30:22 PM:DEBUG [logger_base.py:15] Mensaje a nivel debug
12:30:22 PM:INFO [logger_base.py:16] Mensaje a nivel info
12:30:22 PM:WARNING [logger_base.py:17] Mensaje a nivel warning
12:30:22 PM:ERROR [logger_base.py:18] Mensaje a nivel error
12:30:22 PM:CRITICAL [logger_base.py:19] Mensaje a nivel critical
11:03:12 AM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
11:04:52 AM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
11:06:27 AM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
11:06:27 AM:DEBUG [Persona.py:55] 
            Id Persona: Jose,
            Nombre: Lepez,
            Apellido: ljose@gmail.com,
            Email: None
        
11:07:07 AM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
11:07:07 AM:DEBUG [Persona.py:55] 
            Id Persona: None,
            Nombre: Jose,
            Apellido: Lepez,
            Email: ljose@gmail.com
        
11:10:10 AM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@gmail.com
        
11:10:10 AM:DEBUG [Persona.py:55] 
            Id Persona: None,
            Nombre: Jose,
            Apellido: Lepez,
            Email: ljose@gmail.com
        
11:10:10 AM:DEBUG [Persona.py:57] 
            Id Persona: 1,
            Nombre: None,
            Apellido: None,
            Email: None
        
11:35:23 AM:DEBUG [conexion.py:24] Conexion exitosa: <connection object at 0x00000240D2F9DCF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:37:33 AM:DEBUG [conexion.py:24] Conexion exitosa: <connection object at 0x00000240C5F9DCF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:37:33 AM:ERROR [conexion.py:40] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
11:39:18 AM:DEBUG [conexion.py:24] Conexion exitosa: <connection object at 0x00000278FFD2DCF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:39:18 AM:ERROR [conexion.py:40] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
11:39:37 AM:DEBUG [conexion.py:24] Conexion exitosa: <connection object at 0x0000022AEBC4DCF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
11:39:37 AM:DEBUG [conexion.py:37] Se abrio correctamente el cursor: <cursor object at 0x0000022AEB95B4C0; closed: 0>
